version: '2'

services:

  app:
    image: eeacms/art17-consultation:latest
    depends_on:
    - db
    environment:
      - MIGRATE=no
    env_file:
    - ./docker/app.env
    - ./docker/db.env
    volumes:
    - ./art17:/var/local/art17/art17
    - ./instance:/var/local/art17/instance
    - ./alembic:/var/local/art17/alembic
    - ./migrations:/var/local/art17/migrations

  db:
    image: postgres:13
    container_name: art17.db 
    environment:
      TZ: Europe/Copenhagen
    env_file:
    - ./docker/db.env
    volumes:
    - psqldata:/var/lib/postgresql/data
    - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
