version: '2'

services:

  art17-app:
    image: eeacms/art17-consultation:latest
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - db
    env_file:
    - ../art17.staging.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - staticdata:/var/local/art17/art17/static
    - maps:/var/local/art17-data/maps
    - factsheets:/var/local/art17-data/factsheets

  art17-static:
    image: nginx:alpine
    depends_on:
    - art17-app
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - nginx:/etc/nginx/conf.d
    - staticdata:/var/local/art17/art17/static:ro
    - maps:/var/local/art17-data/maps:ro
    - factsheets:/var/local/art17-data/factsheets:ro

  db:
    image: postgres:13
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - psqldata:/var/lib/postgresql/data
    - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  rsync-server:
    image: eeacms/rsync:latest
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - art17-app
    - db
    ports:
    - "2222:22/tcp"
    command:
    - server
    env_file:
    - ../rsync.key
    environment:
      TZ: Europe/Copenhagen
    tty: true
    stdin_open: true
    volumes:
    - nginx:/etc/nginx/conf.d
    - psqldata:/var/lib/postgresql/data
    - maps:/var/local/maps

volumes:
  nginx:
    driver: rancher-nfs
  staticdata:
    driver: rancher-nfs
  psqldata:
    driver: rancher-nfs
  maps:
    driver: rancher-nfs
  factsheets:
    driver: rancher-nfs
